# Generated by Django 4.2.7 on 2023-11-06 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(default='Enter the description of the task:'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Enter the title of task:', max_length=30),
        ),
    ]
