# Generated by Django 4.2.7 on 2023-11-07 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_creation_date_alter_todo_body_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 5, 51, 46, 579834, tzinfo=datetime.timezone.utc)),
        ),
    ]
